name: Ubuntu continuous integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Install Boost.Test
      run: sudo apt-get --quiet --yes install libboost-test-dev
    - name: Environment variables
      run: make env; make TOOLSET=gcc versions; make TOOLSET=clang versions
    - name: Unit tests with gcc
      run: make -rj2 TOOLSET=gcc example run_tests
    - name: Unit tests with clang
      run: make -rj2 TOOLSET=clang example run_tests
